package com.mycompany.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;


public class AplicarFiltroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AplicarFiltroView
     */
    public AplicarFiltroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlFiltros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ckbAzul = new javax.swing.JCheckBox();
        ckbVerde = new javax.swing.JCheckBox();
        ckbVermelha = new javax.swing.JCheckBox();
        ckbEspelhada = new javax.swing.JCheckBox();
        ckbRotacao = new javax.swing.JCheckBox();
        ckbNegativo = new javax.swing.JCheckBox();
        ckbSepia = new javax.swing.JCheckBox();
        ckbPixelar = new javax.swing.JCheckBox();
        ckbTonsCinza = new javax.swing.JCheckBox();
        ckbBrilho = new javax.swing.JCheckBox();
        cmbxFiltrosPreDefinidos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jBtnFechar = new javax.swing.JButton();
        jBtnRestaurar = new javax.swing.JButton();
        jBtnDesfazer = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 248, 248));
        setClosable(true);
        setIconifiable(true);
        setTitle("Aplicação de Filtros em uma imagem");

        jPnlFiltros.setBackground(new java.awt.Color(248, 248, 248));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setText("Filtros");

        ckbAzul.setBackground(new java.awt.Color(248, 248, 248));
        ckbAzul.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbAzul.setText("Imagem Azul");

        ckbVerde.setBackground(new java.awt.Color(248, 248, 248));
        ckbVerde.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbVerde.setText("Imagem Verde");

        ckbVermelha.setBackground(new java.awt.Color(248, 248, 248));
        ckbVermelha.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbVermelha.setText("Imagem Vermelha");

        ckbEspelhada.setBackground(new java.awt.Color(248, 248, 248));
        ckbEspelhada.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbEspelhada.setText("Imagem espelhada");

        ckbRotacao.setBackground(new java.awt.Color(248, 248, 248));
        ckbRotacao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbRotacao.setText("Rotação da imagem em graus º");

        ckbNegativo.setBackground(new java.awt.Color(248, 248, 248));
        ckbNegativo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbNegativo.setText("Negativo da imagem");

        ckbSepia.setBackground(new java.awt.Color(248, 248, 248));
        ckbSepia.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbSepia.setText("Aplicar a cor Sépia");

        ckbPixelar.setBackground(new java.awt.Color(248, 248, 248));
        ckbPixelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbPixelar.setText("Pixelar imagem");

        ckbTonsCinza.setBackground(new java.awt.Color(248, 248, 248));
        ckbTonsCinza.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbTonsCinza.setText("Tons de Cinza");

        ckbBrilho.setBackground(new java.awt.Color(248, 248, 248));
        ckbBrilho.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ckbBrilho.setText("Aplicar Brilho");

        javax.swing.GroupLayout jPnlFiltrosLayout = new javax.swing.GroupLayout(jPnlFiltros);
        jPnlFiltros.setLayout(jPnlFiltrosLayout);
        jPnlFiltrosLayout.setHorizontalGroup(
            jPnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFiltrosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckbAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbVermelha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbEspelhada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbRotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbNegativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbSepia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbPixelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbTonsCinza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbBrilho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPnlFiltrosLayout.setVerticalGroup(
            jPnlFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFiltrosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ckbAzul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbVermelha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbEspelhada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbRotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbNegativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbSepia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbPixelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbTonsCinza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbBrilho)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbxFiltrosPreDefinidos.setBackground(new java.awt.Color(254, 255, 255));
        cmbxFiltrosPreDefinidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Negativo + Sépia", "2. TonsCinza + Azul", "3. Vermelho + Negativo", "4. Verde + Sépia", "5. Azul + Espelhado", "6. Vermelho + Sépia" }));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Conjunto de Filtros pré-definidos");

        jBtnFechar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnFechar.setText("Fechar");

        jBtnRestaurar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnRestaurar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnRestaurar.setText("Restaurar Padrão");

        jBtnDesfazer.setBackground(new java.awt.Color(248, 248, 248));
        jBtnDesfazer.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnDesfazer.setText("Desfazer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbxFiltrosPreDefinidos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnDesfazer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnFechar)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxFiltrosPreDefinidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jBtnRestaurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnDesfazer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPnlFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckbAzul;
    private javax.swing.JCheckBox ckbBrilho;
    private javax.swing.JCheckBox ckbEspelhada;
    private javax.swing.JCheckBox ckbNegativo;
    private javax.swing.JCheckBox ckbPixelar;
    private javax.swing.JCheckBox ckbRotacao;
    private javax.swing.JCheckBox ckbSepia;
    private javax.swing.JCheckBox ckbTonsCinza;
    private javax.swing.JCheckBox ckbVerde;
    private javax.swing.JCheckBox ckbVermelha;
    private javax.swing.JComboBox<String> cmbxFiltrosPreDefinidos;
    private javax.swing.JButton jBtnDesfazer;
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnRestaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPnlFiltros;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getCkbAzul() {
        return ckbAzul;
    }

    public JCheckBox getCkbBrilho() {
        return ckbBrilho;
    }

    public JCheckBox getCkbEspelhada() {
        return ckbEspelhada;
    }

    public JCheckBox getCkbNegativo() {
        return ckbNegativo;
    }

    public JCheckBox getCkbPixelar() {
        return ckbPixelar;
    }

    public JCheckBox getCkbRotacao() {
        return ckbRotacao;
    }

    public JCheckBox getCkbSepia() {
        return ckbSepia;
    }

    public JCheckBox getCkbTonsCinza() {
        return ckbTonsCinza;
    }

    public JCheckBox getCkbVerde() {
        return ckbVerde;
    }

    public JCheckBox getCkbVermelha() {
        return ckbVermelha;
    }

    public JComboBox<String> getCmbxFiltrosPreDefinidos() {
        return cmbxFiltrosPreDefinidos;
    }

    public JButton getjBtnDesfazer() {
        return jBtnDesfazer;
    }

    public JButton getjBtnFechar() {
        return jBtnFechar;
    }

    public JButton getjBtnRestaurar() {
        return jBtnRestaurar;
    }

    public JPanel getjPnlFiltros() {
        return jPnlFiltros;
    }

    public JLabel getLblImagem() {
        return lblImagem;
    }
    
    
}
