package com.mycompany.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;


public class PermissoesView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PermissoesView
     */
    public PermissoesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jCkVisualizar = new javax.swing.JCheckBox();
        jCkExcluir = new javax.swing.JCheckBox();
        jCkCompartilhar = new javax.swing.JCheckBox();
        jCkAplicarFiltro = new javax.swing.JCheckBox();
        jBtnSalvar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(248, 248, 248));
        setIconifiable(true);
        setTitle("Gerenciar Permissões");

        jLabel1.setBackground(new java.awt.Color(248, 248, 248));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Permissões do usuário");

        lblUsuario.setBackground(new java.awt.Color(248, 248, 248));
        lblUsuario.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("Usuário");

        jCkVisualizar.setBackground(new java.awt.Color(248, 248, 248));
        jCkVisualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCkVisualizar.setText("Visualizar");

        jCkExcluir.setBackground(new java.awt.Color(248, 248, 248));
        jCkExcluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCkExcluir.setText("Excluir");

        jCkCompartilhar.setBackground(new java.awt.Color(248, 248, 248));
        jCkCompartilhar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCkCompartilhar.setText("Compartilhar");

        jCkAplicarFiltro.setBackground(new java.awt.Color(248, 248, 248));
        jCkAplicarFiltro.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jCkAplicarFiltro.setText("Aplicar Filtro");

        jBtnSalvar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnSalvar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnSalvar.setText("Salvar");

        jBtnCancelar.setBackground(new java.awt.Color(248, 248, 248));
        jBtnCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBtnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCkVisualizar)
                                .addComponent(jCkAplicarFiltro)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCkExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCkCompartilhar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jCkVisualizar)
                .addGap(18, 18, 18)
                .addComponent(jCkExcluir)
                .addGap(18, 18, 18)
                .addComponent(jCkCompartilhar)
                .addGap(18, 18, 18)
                .addComponent(jCkAplicarFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JCheckBox jCkAplicarFiltro;
    private javax.swing.JCheckBox jCkCompartilhar;
    private javax.swing.JCheckBox jCkExcluir;
    private javax.swing.JCheckBox jCkVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

    public JButton getjBtnCancelar() {
        return jBtnCancelar;
    }

    public JButton getjBtnSalvar() {
        return jBtnSalvar;
    }

    public JCheckBox getjCkAplicarFiltro() {
        return jCkAplicarFiltro;
    }

    public JCheckBox getjCkCompartilhar() {
        return jCkCompartilhar;
    }

    public JCheckBox getjCkExcluir() {
        return jCkExcluir;
    }

    public JCheckBox getjCkVisualizar() {
        return jCkVisualizar;
    }

    public JLabel getLblUsuario() {
        return lblUsuario;
    }

    

}
